# Generated by Django 3.2.16 on 2022-11-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='ball_id',
        ),
    ]
