# Generated by Django 3.2.16 on 2022-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0002_remove_deliveries_ball_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveIntegerField(verbose_name='match_id')),
                ('season', models.PositiveIntegerField(verbose_name='season')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('date', models.DateField(auto_now=True, verbose_name='date')),
                ('team1', models.CharField(max_length=255, verbose_name='team1')),
                ('team2', models.CharField(max_length=255, verbose_name='team2')),
                ('toss_winner', models.CharField(max_length=255, verbose_name='toss_winner')),
                ('toss_decision', models.CharField(max_length=255, verbose_name='toss_decision')),
                ('result', models.CharField(max_length=255, verbose_name='result')),
                ('dl_applied', models.PositiveIntegerField(verbose_name='dl_applied')),
                ('winner', models.CharField(max_length=255, verbose_name='winner')),
                ('win_by_runs', models.PositiveIntegerField(verbose_name='win_by_runs')),
                ('win_by_wickets', models.PositiveIntegerField(verbose_name='win_by_wickets')),
                ('player_of_match', models.CharField(max_length=255, verbose_name='player_of_match')),
                ('venue', models.CharField(max_length=255, verbose_name='venue')),
                ('umpire1', models.CharField(max_length=255, verbose_name='umpire1')),
                ('umpire2', models.CharField(max_length=255, verbose_name='umpire2')),
                ('umpire3', models.CharField(max_length=255, verbose_name='umpire3')),
            ],
        ),
    ]
