# Generated by Django 3.2.16 on 2022-11-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0003_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='umpire3',
        ),
    ]
