# Generated by Django 3.2.16 on 2022-11-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0004_remove_matches_umpire3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='match_id',
        ),
    ]
