# Generated by Django 3.2.16 on 2022-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0005_remove_matches_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='season',
            field=models.DateField(auto_now=True, verbose_name='season'),
        ),
    ]
