# Generated by Django 3.2.16 on 2022-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0006_alter_matches_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='season',
            field=models.CharField(max_length=255, verbose_name='season'),
        ),
    ]
