# Generated by Django 3.2.16 on 2022-11-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0008_alter_matches_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveries',
            options={'verbose_name': 'Ball By Ball', 'verbose_name_plural': 'Ball by Ball Data'},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches Data'},
        ),
    ]
